---
language: python
python: "2.7"
python: "3.5"
install:
  - pip install ansible
script:
  # Prepare tests
  - echo localhost > inventory
  # Check syntax
  - ansible-playbook --syntax-check -i inventory test-$TRAVIS_PYTHON_VERSION.yml
  # Test provisioning role
  - ansible-playbook -i inventory test-$TRAVIS_PYTHON_VERSION.yml --connection=local --sudo

notifications:
  webhooks:
  # trigger Buildtime Trend Service to parse Travis CI log and send result to Keen.io
  - https://buildtimetrend-dev.herokuapp.com/travis
  - https://buildtimetrend.herokuapp.com/travis
