---
language: python
python: "2.7"
install:
  - pip install ansible
script:
  # Prepare tests
  - echo localhost > inventory
  # Check syntax
  - ansible-playbook --syntax-check -i inventory test.yml
  # Test provisioning role
  - ansible-playbook -i inventory test.yml --connection=local
