---
- hosts: all
  tasks:
    - include: tasks/main.yml
  vars_files:
    - vars/main.yml
  vars:
    python_deps_extra_libs:
      - libxml2-dev
      - libxslt1-dev
    python_dep_requirements:
      - "/home/travis/build/buildtimetrend/ansible_python_deps/test_requirements.txt"
