---
- hosts: all
  roles:
    - { role: python_deps, python_deps_extra_libs: "{{ extra_libs }}", python_deps_requirements: "{{ reqs }}"}
    - { role: python_deps, python_deps_extra_libs: "{{ extra_libs }}", python_deps_requirements: "{{ reqs }}", python_deps_python_version: "2" }

  vars:
    extra_libs:
      - libxml2-dev
      - libxslt1-dev
    reqs:
      - "/home/travis/build/buildtimetrend/ansible_python_deps/test_requirements.txt"
