---
- hosts: all
  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/main.yml
      vars:
        python_deps_extra_libs:
          - libxml2-dev
          - libxslt1-dev
        python_deps_requirements:
          - "/home/travis/build/buildtimetrend/ansible_python_deps/test_requirements.txt"
